## 6.1. INTRODUCTION: SEQUENCES
---

mempelajari operator-operator yang dapat digunakan dalam *sequences* beserta beberapa *function* dan perbedaan dari list dan strings

---
### 6.1.1 Learing Goals
- To understand different operations that can be performed on strings, lists, and tuples
- To distinguish between different uses of [] in Python
---
### 6.1.2 Tujuan
- Predict the output of split and join operations
- Read and write expressions that use slices
- Read and write expressions that use concatenation and repetition

## 6.2. Strings dan List
---
Strings merupakan kumpulan karakter yang berurutan dari kiri ke kanan. strings tanpa karakter disebut dengan *empty string* dan biasa diwakili degan '' atau "". sedangkan List adalah kumpulan nilai berurutan yang dapat memiliki macam-macam tipe data (tidak hanya strings), dimana setiap nilainya diidentifikasi dengan index dan nilainya disebut elemen.

In [1]:
s = 'Hello world'
print(type(s))

<class 'str'>

In [4]:
t = [10, 20, 30, 40]
u = ["spam", "bungee", "swallow"]

print(type(u), type(t))

<class 'list'> <class 'list'>

In [5]:
a = ["hello", 2.0, 5, [10, 20]]

print(a[1]) #index 1 = elemen list ke 2

2.0

## Tuples
---
merupakan urutan nilai yang dapat terdiri dari tipe data apapun seperti list namun urutannya dipisahkan oleh koma (,) dan diapit oleh tanda kurung (list menggunakan []). selain perbedaan tanda yang mengapit, tuple tidak dapat diubah setelah dibuat sedangkan list dapat diubah.

In [7]:
julia = ("Julia", "Roberts", 1967, "Duplicity", 2009, "Actress", "Atlanta, Georgia")

print(type(julia))

<class 'tuple'>

In [8]:
t = (5,)
print(type(t))

x = (5)
print(type(x))

<class 'tuple'>
<class 'int'>

## 6.3. Index Operator: Strings, List, Tuple
---
indeks operator dalam Python menggunakan tanda kurung siku ([]) untuk memilih satu karakter dalam string. karakter dalam string sendiri diakses melalui posisi atau nilai indeksnya dan dimulai dari 0.

In [9]:
school = "Luther College"
m = school[2] #indeks ke 3
print(m)

lastchar = school[-1] #indeks ke 14
print(lastchar)

t
e

In [10]:
numbers = [17, 123, 87, 34, 66, 8398, 44]
print(numbers[2])
print(numbers[9-8])
print(numbers[-2])

87
123
8398

In [11]:
prices = (1.99, 2.00, 5.50, 20.95, 100.98)
print(prices[0])
print(prices[-1])
print(prices[3-5])

1.99
100.98
20.95

In [12]:
s = "python rocks"
print(s[3])

h

In [13]:
s = "python rocks"
print(s[2] + s[-4])

to

In [14]:
alist = [3, 67, "cat", [56, 57, "dog"], [ ], 3.14, False]
print(alist[5])

3.14

### Exercise
---
Assign the value of the 34th element of lst to the variable output.

In [16]:
lst = ["hi", "morning", "dog", "506", "caterpillar", "balloons", 106, "yo-yo", "python", "moon", "water", "sleepy", "daffy", 45, "donald", "whiteboard", "glasses", "markers", "couches", "butterfly", "100", "magazine", "door", "picture", "window", ["Olympics", "handle"], "chair", "pages", "readings", "burger", "juggle", "craft", ["store", "poster", "board"], "laptop", "computer", "plates", "hotdog", "salad", "backpack", "zipper", "ring", "watch", "finger", "bags", "boxes", "pods", "peas", "apples", "horse", "guinea pig", "bowl", "EECS"]
output=lst[33]
print(output)

laptop

---
Assign the value of the 23rd element of l to the variable checking.

In [17]:
l = ("hi", "goodbye", "python", "106", "506", 91, ['all', 'Paul', 'Jackie', "UMSI", 1, "Stephen", 4.5], 109, "chair", "pizza", "wolverine", 2017, 3.92, 1817, "account", "readings", "papers", 12, "facebook", "twitter", 193.2, "snapchat", "leaders and the best", "social", "1986", 9, 29, "holiday", ["women", "olympics", "gold", "rio", 21, "2016", "men"], "26trombones")

checking=l[22]
print(checking)

leaders and the best

---
Assign the value of the last chacter of lst to the variable output. Do this so that the length of lst doesn’t matter.

In [18]:
lst = "Every chess or checkers game begins from the same position and has a finite number of moves that can be played. While the number of possible scenarios and moves is quite large, it is still possible for computers to calculate that number and even be programmed to respond well against a human player..."

output=lst[-1]
print(output)

.

## 6.4. Disabmiguating []: creation vs indexing
---
memahami perbedaan penggunaan [], yaitu
1. membuat list
2. pengindeksan

In [1]:
new_lst = [] #empty list tidak dapat diindeks

In [2]:
new_lst = ["NFLX", "AMZN", "GOOGL", "DIS", "XOM"]
part_of_new_lst = new_lst[0] #index 0 = data ke 1

In [3]:
lst = [0]
n_lst = lst[0]

print(lst)
print(n_lst)

[0]
0

## 6.5. Length
---
length atau panjang data dapat dicari menggunakan *function* len() namun hanya dapat digunakan pada data dengan tipe string. pada *function* ini, nilai yang dikembalikan adalah banyaknya karakter dalam string.

In [4]:
fruit = "Banana"
print(len(fruit))

6

In [5]:
fruit = "Banana"
sz = len(fruit)
last = fruit[sz]       #error, dalam fruit tidak ada index sz
print(last)

IndexError: string index out of range

In [6]:
fruit = "Banana"
sz = len(fruit)
lastch = fruit[sz-1]
print(lastch)

a

In [8]:
lastch = fruit[len(fruit)-1]
print(lastch)

a

In [11]:
fruit = "grape"
midchar = fruit[len(fruit)//2] #index tengah

print(midchar)

a

In [12]:
alist =  ["hello", 2.0, 5]
print(len(alist))
print(len(alist[0]))

3
5

In [13]:
s = "python rocks"
print(len(s))

12

In [14]:
alist = [3, 67, "cat", 3.14, False]
print(len(alist))

5

---
Assign the number of elements in lst to the variable output.

In [16]:
lst = ["hi", "morning", "dog", "506", "caterpillar", "balloons", 106, "yo-yo", "python", "moon", "water", "sleepy", "daffy", 45, "donald", "whiteboard", "glasses", "markers", "couches", "butterfly", "100", "magazine", "door", "picture", "window", ["Olympics", "handle"], "chair", "pages", "readings", "burger", "juggle", "craft", ["store", "poster", "board"], "laptop", "computer", "plates", "hotdog", "salad", "backpack", "zipper", "ring", "watch", "finger", "bags", "boxes", "pods", "peas", "apples", "horse", "guinea pig", "bowl", "EECS"]

output=len(lst)
print(output)

52

## 6.6. The Slice Operator
---
substring dari string disebut dengan slice. slice juga dapat diartikan sebagai mengambil karakter dari suatu string. operator dalam string adalah [n:m] dimana n merupakan awalan string yang diambil sampai karakter sebelum m.

In [20]:
julia = ("julia", "robert", "1967", "duplicity",2009, "actress", "atlanta, geogia")

print(julia[2]) #indexing
print(julia[2:6]) #slicing
print(len(julia)) #banyak karakter

julia=julia[:3]+("eat pray love", 2010)+julia[5:]
print(julia)

1967
('1967', 'duplicity', 2009, 'actress')
7
('julia', 'robert', '1967', 'eat pray love', 2010, 'actress', 'atlanta, geogia')

In [21]:
singers = "Peter, Paul, and Mary"
print(singers[0:5])
print(singers[7:11])
print(singers[17:21])

Peter
Paul
Mary

In [22]:
fruit = "banana"
print(fruit[:3]) #slice 3 awal
print(fruit[3:]) #slice 3 akhir

ban
ana

In [24]:
fruit[:] #mengambil seluruh karakter

'banana'

In [26]:
#slice dalam list
a_list = ['a', 'b', 'c', 'd', 'e', 'f']
print(a_list[1:3])
print(a_list[:4])
print(a_list[3:])
print(a_list[:])

['b', 'c']
['a', 'b', 'c', 'd']
['d', 'e', 'f']
['a', 'b', 'c', 'd', 'e', 'f']

In [27]:
#slice dalam tuple
julia = ("Julia", "Roberts", 1967, "Duplicity", 2009, "Actress", "Atlanta, Georgia")
print(julia[2])
print(julia[2:6])

print(len(julia))

julia = julia[:3] + ("Eat Pray Love", 2010) + julia[5:]
print(julia)

1967
(1967, 'Duplicity', 2009, 'Actress')
7
('Julia', 'Roberts', 1967, 'Eat Pray Love', 2010, 'Actress', 'Atlanta, Georgia')

In [28]:
s = "python rocks"
print(s[3:8])

hon r

In [29]:
alist = [3, 67, "cat", [56, 57, "dog"], [ ], 3.14, False]
print(alist[4:])

[[], 3.14, False]

In [30]:
L = [0.34, '6', 'SI106', 'Python', -2]
print(len(L[1:-1]))

3

---
Create a new list using the 9th through 12th elements (four items in all) of new_lst and assign it to the variable sub_lst.

In [31]:
new_lst = ["computer", "luxurious", "basket", "crime", 0, 2.49, "institution", "slice", "sun", ["water", "air", "fire", "earth"], "games", 2.7, "code", "java", ["birthday", "celebration", 1817, "party", "cake", 5], "rain", "thunderstorm", "top down"]

sub_lst=new_lst[8:12]
print(sub_lst)

['sun', ['water', 'air', 'fire', 'earth'], 'games', 2.7]

## 6.7. Concatenation and Repetition
---
penggabungan dan perulangan. dalam jenis data String penggabungannya dapat dilajukan dengan menggunakan operator (+). hal ini juga berlaku pada operator-operator lain seperti (*) dimana operator tersebut akan melakukan perulangan sebanyak n kali.

In [32]:
fruit = ["apple","orange","banana","cherry"]
print([1,2] + [3,4])
print(fruit+[6,7,8,9])

print([0] * 4)

[1, 2, 3, 4]
['apple', 'orange', 'banana', 'cherry', 6, 7, 8, 9]
[0, 0, 0, 0]

In [33]:
alist = [1,3,5]
blist = [2,4,6]
print(alist + blist)

[1, 3, 5, 2, 4, 6]

In [34]:
alist = [1,3,5]
print(alist * 3)

[1, 3, 5, 1, 3, 5, 1, 3, 5]

## 6.8. Count and Index
---
salah satu *built-in function* yang sering digunakan adalah *count* dan *index*. *function* ini dapat digunakan untuk tipe data string dan list.
---
**Count**
merupakan fungsi dengan 1 argumen yang berisi hal yang akan dihitung. fungsi ini mengembalikan banyaknya argumen yang muncul dalam suatu string atau list. argumen dalam count hanya dapat berisi string.
**Index**
sama seperti fungsi *count*, index memiliki 1 argumen. index mengembalikan index paling kiri dari argumen. index dapat digunakan baik list maupun string.

In [1]:
a = "I have had n apple on my desk before!"
print(a.count("e")) #count e
print(a.count("ha")) #count word ha

5
2

In [3]:
z = ['atoms', 4, 'neutron', 6, 'proton', 4, 'electron', 4, 'electron', 'atoms']
print(z.count("4")) #count string
print(z.count(4)) #count int
print(z.count("a"))
print(z.count("electron"))

0
3
0
2

In [4]:
music = "Pull out your music and dancing can begin"
bio = ["Metatarsal", "Metatarsal", "Fibula", [], "Tibia", "Tibia", 43, "Femur", "Occipital", "Metatarsal"]

print(music.index("m"))
print(music.index("your"))

print(bio.index("Metatarsal"))
print(bio.index([]))
print(bio.index(43))

14
9
0
3
6

In [5]:
seasons = ["winter", "spring", "summer", "fall"]

print(seasons.index("autumn"))  #Error, tidak ada autumn

ValueError: 'autumn' is not in list

In [7]:
qu = "wow, welcome week!"
ty = qu.index("we")

print(ty)

5

In [9]:
qu = "wow, welcome week! Were you wanting to go?"
ty = qu.count("we")

print(ty)

2

In [11]:
rooms = ['bathroom', 'kitchen', 'living room', 'bedroom', 'closet', "foyer"]
ht = rooms.index("garden")

print(ht)

ValueError: 'garden' is not in list

## Split dan Join Strings
---
fungsi split memisahkan string menjadi list dengan kata kata. argumen dalam split dapat berupa **delimiter** yang dapat digunakan untuk memisahkan string berdasarkan kata dalam argumen. kebelikan dari split adalah join. join adalah fungsi yang digunakan untuk menyatukan elemen dengan argumen separator yang dapat dipilih.

In [12]:
song = "The rain in Spain..."
wds = song.split() #split by space
print(wds)

['The', 'rain', 'in', 'Spain...']

In [13]:
song = "The rain in Spain..."
wds = song.split('ai') #split by the word ai
print(wds)

['The r', 'n in Sp', 'n...']

In [14]:
wds = ["red", "blue", "green"]
glue = ';'
s = glue.join(wds) #menyatukan
print(s)
print(wds)

print("***".join(wds))
print("".join(wds))

red;blue;green
['red', 'blue', 'green']
red***blue***green
redbluegreen

---
Create a new list of the 6th through 13th elements of lst (eight items in all) and assign it to the variable output.

In [15]:
lst = ["swimming", 2, "water bottle", 44, "lollipop", "shine", "marsh", "winter", "donkey", "rain", ["Rio", "Beijing", "London"], [1,2,3], "gold", "bronze", "silver", "mathematician", "scientist", "actor", "actress", "win", "cell phone", "leg", "running", "horse", "socket", "plug", ["Phelps", "le Clos", "Lochte"], "drink", 22, "happyfeet", "penguins"]

output=lst[5:13]
print(output)

['shine', 'marsh', 'winter', 'donkey', 'rain', ['Rio', 'Beijing', 'London'], [1, 2, 3], 'gold']

---
Create a variable output and assign it to a list whose elements are the words in the string str1.

In [16]:
str1 = "OH THE PLACES YOU'LL GO"

output= str1.split()
print(output)

['OH', 'THE', 'PLACES', "YOU'LL", 'GO']

## 6.10 EXERCISE
---

seq-11-1: Write a program that will print out the length of each item in the list as well as the first and last characters of the item.

In [17]:
weather = ["sunny", "cloudy", "partially sunny", "rainy", "storming", "windy", "foggy", "snowy", "hailing"]

for condition in weather :
    print("the word is", len(condition), "characters")
    first_char = condition[0]
    last_char = condition[-1]
    
    print("the first char is:" + first_char)
    print("the last char is:" + last_char)

the word is 5 characters
the first char is:s
the last char is:y
the word is 6 characters
the first char is:c
the last char is:y
the word is 15 characters
the first char is:p
the last char is:y
the word is 5 characters
the first char is:r
the last char is:y
the word is 8 characters
the first char is:s
the last char is:g
the word is 5 characters
the first char is:w
the last char is:y
the word is 5 characters
the first char is:f
the last char is:y
the word is 5 characters
the first char is:s
the last char is:y
the word is 7 characters
the first char is:h
the last char is:g

---
seq-11-2: Write code to determine how many t's are in the following sentences.

In [19]:
phrases = ["My, what a lovely day today is!", "Have you mastered cooking yet? Atasty treat could be in your future.", "Have you ever seen the leaves change color?"]

for sentence in phrases:
    print(sentence.count("t"))

2
7
1

## 6.11 Chapter Assessment
---

In [20]:
let = "z"
let_two = "p"
c = let_two + let
m = c*5
print(m)

pzpzpzpzpz

---
Write a program that extracts the last three items in the list sports and assigns it to the variable last. Make sure to write your code so that it works no matter how many items are in the list.

In [23]:
sports = ['cricket', 'football', 'volleyball', 'baseball', 'softball', 'track and field', 'curling', 'ping pong', 'hockey']

last=sports[-3:]
print(last)

['curling', 'ping pong', 'hockey']

---
Write code that combines the following variables so that the sentence “You are doing a great job, keep it up!” is assigned to the variable message. Do not edit the values assigned to by, az, io, or qy.

In [24]:
by = "You are"
az = "doing a great "
io = "job"
qy = "keep it up!"

message=by+" "+az+io+", "+qy
message="".join(message)
print(message)

You are doing a great job, keep it up!

---
sequences-10-2: What will the output be for the following code?

In [25]:
ls = ['run', 'world', 'travel', 'lights', 'moon', 'baseball', 'sea']
new = ls[2:4]
print(new)

['travel', 'lights']

---
sequences-10-3: What is the type of m?

In [27]:
l = ['w', '7', 0, 9]
m = l[1:2]

print(type(m))

<class 'list'>

In [29]:
l = ['w', '7', 0, 9]
m = l[1]

print(type(m))

<class 'str'>

In [30]:
b = "My, what a lovely day"
x = b.split(',')

print(type(x))

<class 'list'>

In [32]:
b = "My, what a lovely day"
x = b.split(',')
z = "".join(x)
y = z.split()
a = "".join(y)

print(type(a))

<class 'str'>

---
Write code to determine how many 9’s are in the list nums and assign that value to the variable how_many. Do not use a for loop to do this.

In [33]:
nums = [4, 2, 23.4, 9, 545, 9, 1, 234.001, 5, 49, 8, 9 , 34, 52, 1, -2, 9.1, 4]

how_many=nums.index(9)
print(how_many)

3

---
Write code that uses slicing to get rid of the the second 8 so that here are only two 8’s in the list bound to the variable nums.

In [37]:
nums = [4, 2, 8, 23.4, 8, 9, 545, 9, 1, 234.001, 5, 49, 8, 9 , 34, 52, 1, -2, 9.1, 4]

nums = nums[0:3]+nums[5:]
print(nums)

[4, 2, 8, 9, 545, 9, 1, 234.001, 5, 49, 8, 9, 34, 52, 1, -2, 9.1, 4]

---
Assign the last element of lst to the variable end_elem. Do this so that it works no matter how long lst is.

In [34]:
lst = ["hi", "goodbye", "python", "106", "506", 91, ['all', 'Paul', 'Jackie', "UMSI", 1, "Stephen", 4.5], 109, "chair", "pizza", "wolverine", 2017, 3.92, 1817, "account", "readings", "papers", 12, "facebook", "twitter", 193.2, "snapchat", "leaders and the best", "social", "1986", 9, 29, "holiday", ["women", "olympics", "gold", "rio", 21, "2016", "men"], "26trombones"]

end_elem=lst[-1]
print(end_elem)

26trombones

---
Assign the number of elements in lst to the variable num_lst.

In [35]:
lst = ["hi", "goodbye", "python", "106", "506", 91, ['all', 'Paul', 'Jackie', "UMSI", 1, "Stephen", 4.5], 109, "chair", "pizza", "wolverine", 2017, 3.92, 1817, "account", "readings", "papers", 12, "facebook", "twitter", 193.2, "snapchat", "leaders and the best", "social", "1986", 9, 29, "holiday", ["women", "olympics", "gold", "rio", 21, "2016", "men"], "26trombones"]

num_lst=len(lst)
print(num_lst)

30

---
Create a variable called wrds and assign to it a list whose elements are the words in the string sent. Do not worry about punctuation.

In [36]:
sent = "The bicentennial for our university was in 2017"
wrds=sent.split()
print(wrds)

['The', 'bicentennial', 'for', 'our', 'university', 'was', 'in', '2017']

---
addition_str is a string with a list of numbers separated by the + sign. Write code that uses the accumulation pattern to take the sum of all of the numbers and assigns it to sum_val (an integer). (You should use the .split("+") function to split by "+" and int() to cast to an integer).

In [9]:
addition_str = "2+5+10+20"
int(addition_str.split('+'))

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'