## 6.1. INTODUCTION: SEQUENCES
---

mempelajari operator-operator yang dapat digunakan dalam *sequences* beserta beberapa *function* dan perbedaan dari list dan strings

---
### 6.1.1 Learing Goals
- To understand different operations that can be performed on strings, lists, and tuples
- To distinguish between different uses of [] in Python
---
### 6.1.2 Tujuan
- Predict the output of split and join operations
- Read and write expressions that use slices
- Read and write expressions that use concatenation and repetition

## 6.2. Strings dan List
---
Strings merupakan kumpulan karakter yang berurutan dari kiri ke kanan. strings tanpa karakter disebut dengan *empty string* dan biasa diwakili degan '' atau "". sedangkan List adalah kumpulan nilai berurutan yang dapat memiliki macam-macam tipe data (tidak hanya strings), dimana setiap nilainya diidentifikasi dengan index dan nilainya disebut elemen.

In [1]:
s = 'Hello world'
print(type(s))

<class 'str'>

In [4]:
t = [10, 20, 30, 40]
u = ["spam", "bungee", "swallow"]

print(type(u), type(t))

<class 'list'> <class 'list'>

In [5]:
a = ["hello", 2.0, 5, [10, 20]]

print(a[1]) #index 1 = elemen list ke 2

2.0

## Tuples
---
merupakan urutan nilai yang dapat terdiri dari tipe data apapun seperti list namun urutannya dipisahkan oleh koma (,) dan diapit oleh tanda kurung (list menggunakan []). selain perbedaan tanda yang mengapit, tuple tidak dapat diubah setelah dibuat sedangkan list dapat diubah.

In [7]:
julia = ("Julia", "Roberts", 1967, "Duplicity", 2009, "Actress", "Atlanta, Georgia")

print(type(julia))

<class 'tuple'>

In [8]:
t = (5,)
print(type(t))

x = (5)
print(type(x))

<class 'tuple'>
<class 'int'>