## 6.1. INTODUCTION: SEQUENCES
---

mempelajari operator-operator yang dapat digunakan dalam *sequences* beserta beberapa *function* dan perbedaan dari list dan strings

---
### 6.1.1 Learing Goals
- To understand different operations that can be performed on strings, lists, and tuples
- To distinguish between different uses of [] in Python
---
### 6.1.2 Tujuan
- Predict the output of split and join operations
- Read and write expressions that use slices
- Read and write expressions that use concatenation and repetition

## 6.2. Strings dan List
---
Strings merupakan kumpulan karakter yang berurutan dari kiri ke kanan. strings tanpa karakter disebut dengan *empty string* dan biasa diwakili degan '' atau "". sedangkan List adalah kumpulan nilai berurutan yang dapat memiliki macam-macam tipe data (tidak hanya strings), dimana setiap nilainya diidentifikasi dengan index dan nilainya disebut elemen.

In [1]:
s = 'Hello world'
print(type(s))

<class 'str'>

In [4]:
t = [10, 20, 30, 40]
u = ["spam", "bungee", "swallow"]

print(type(u), type(t))

<class 'list'> <class 'list'>

In [5]:
a = ["hello", 2.0, 5, [10, 20]]

print(a[1]) #index 1 = elemen list ke 2

2.0

## Tuples
---
merupakan urutan nilai yang dapat terdiri dari tipe data apapun seperti list namun urutannya dipisahkan oleh koma (,) dan diapit oleh tanda kurung (list menggunakan []). selain perbedaan tanda yang mengapit, tuple tidak dapat diubah setelah dibuat sedangkan list dapat diubah.

In [7]:
julia = ("Julia", "Roberts", 1967, "Duplicity", 2009, "Actress", "Atlanta, Georgia")

print(type(julia))

<class 'tuple'>

In [8]:
t = (5,)
print(type(t))

x = (5)
print(type(x))

<class 'tuple'>
<class 'int'>

## 6.3. Index Operator: Strings, List, Tuple
---
indeks operator dalam Python menggunakan tanda kurung siku ([]) untuk memilih satu karakter dalam string. karakter dalam string sendiri diakses melalui posisi atau nilai indeksnya dan dimulai dari 0.

In [9]:
school = "Luther College"
m = school[2] #indeks ke 3
print(m)

lastchar = school[-1] #indeks ke 14
print(lastchar)

t
e

In [10]:
numbers = [17, 123, 87, 34, 66, 8398, 44]
print(numbers[2])
print(numbers[9-8])
print(numbers[-2])

87
123
8398

In [11]:
prices = (1.99, 2.00, 5.50, 20.95, 100.98)
print(prices[0])
print(prices[-1])
print(prices[3-5])

1.99
100.98
20.95

In [12]:
s = "python rocks"
print(s[3])

h

In [13]:
s = "python rocks"
print(s[2] + s[-4])

to

In [14]:
alist = [3, 67, "cat", [56, 57, "dog"], [ ], 3.14, False]
print(alist[5])

3.14

### Exercise
---
Assign the value of the 34th element of lst to the variable output.

In [16]:
lst = ["hi", "morning", "dog", "506", "caterpillar", "balloons", 106, "yo-yo", "python", "moon", "water", "sleepy", "daffy", 45, "donald", "whiteboard", "glasses", "markers", "couches", "butterfly", "100", "magazine", "door", "picture", "window", ["Olympics", "handle"], "chair", "pages", "readings", "burger", "juggle", "craft", ["store", "poster", "board"], "laptop", "computer", "plates", "hotdog", "salad", "backpack", "zipper", "ring", "watch", "finger", "bags", "boxes", "pods", "peas", "apples", "horse", "guinea pig", "bowl", "EECS"]
output=lst[33]
print(output)

laptop

---
Assign the value of the 23rd element of l to the variable checking.

In [17]:
l = ("hi", "goodbye", "python", "106", "506", 91, ['all', 'Paul', 'Jackie', "UMSI", 1, "Stephen", 4.5], 109, "chair", "pizza", "wolverine", 2017, 3.92, 1817, "account", "readings", "papers", 12, "facebook", "twitter", 193.2, "snapchat", "leaders and the best", "social", "1986", 9, 29, "holiday", ["women", "olympics", "gold", "rio", 21, "2016", "men"], "26trombones")

checking=l[22]
print(checking)

leaders and the best

---
Assign the value of the last chacter of lst to the variable output. Do this so that the length of lst doesnâ€™t matter.

In [18]:
lst = "Every chess or checkers game begins from the same position and has a finite number of moves that can be played. While the number of possible scenarios and moves is quite large, it is still possible for computers to calculate that number and even be programmed to respond well against a human player..."

output=lst[-1]
print(output)

.

## 6.4. Disabmiguating []: creation vs indexing
---
memahami perbedaan penggunaan [], yaitu
1. membuat list
2. pengindeksan

In [1]:
new_lst = [] #empty list tidak dapat diindeks

In [2]:
new_lst = ["NFLX", "AMZN", "GOOGL", "DIS", "XOM"]
part_of_new_lst = new_lst[0] #index 0 = data ke 1

In [3]:
lst = [0]
n_lst = lst[0]

print(lst)
print(n_lst)

[0]
0

## 6.5. Length
---
length atau panjang data dapat dicari menggunakan *function* len() namun hanya dapat digunakan pada data dengan tipe string. pada *function* ini, nilai yang dikembalikan adalah banyaknya karakter dalam string.

In [4]:
fruit = "Banana"
print(len(fruit))

6

In [5]:
fruit = "Banana"
sz = len(fruit)
last = fruit[sz]       #error, dalam fruit tidak ada index sz
print(last)

IndexError: string index out of range

In [6]:
fruit = "Banana"
sz = len(fruit)
lastch = fruit[sz-1]
print(lastch)

a

In [8]:
lastch = fruit[len(fruit)-1]
print(lastch)

a

In [11]:
fruit = "grape"
midchar = fruit[len(fruit)//2] #index tengah

print(midchar)

a

In [12]:
alist =  ["hello", 2.0, 5]
print(len(alist))
print(len(alist[0]))

3
5

In [13]:
s = "python rocks"
print(len(s))

12

In [14]:
alist = [3, 67, "cat", 3.14, False]
print(len(alist))

5

---
Assign the number of elements in lst to the variable output.

In [16]:
lst = ["hi", "morning", "dog", "506", "caterpillar", "balloons", 106, "yo-yo", "python", "moon", "water", "sleepy", "daffy", 45, "donald", "whiteboard", "glasses", "markers", "couches", "butterfly", "100", "magazine", "door", "picture", "window", ["Olympics", "handle"], "chair", "pages", "readings", "burger", "juggle", "craft", ["store", "poster", "board"], "laptop", "computer", "plates", "hotdog", "salad", "backpack", "zipper", "ring", "watch", "finger", "bags", "boxes", "pods", "peas", "apples", "horse", "guinea pig", "bowl", "EECS"]

output=len(lst)
print(output)

52

## 6.6. The Slice Operator
---
substring dari string disebut dengan slice. slice juga dapat diartikan sebagai mengambil karakter dari suatu string. operator dalam string adalah [n:m] dimana n merupakan awalan string yang diambil sampai karakter sebelum m.

In [20]:
julia = ("julia", "robert", "1967", "duplicity",2009, "actress", "atlanta, geogia")

print(julia[2]) #indexing
print(julia[2:6]) #slicing
print(len(julia)) #banyak karakter

julia=julia[:3]+("eat pray love", 2010)+julia[5:]
print(julia)

1967
('1967', 'duplicity', 2009, 'actress')
7
('julia', 'robert', '1967', 'eat pray love', 2010, 'actress', 'atlanta, geogia')

In [21]:
singers = "Peter, Paul, and Mary"
print(singers[0:5])
print(singers[7:11])
print(singers[17:21])

Peter
Paul
Mary

In [22]:
fruit = "banana"
print(fruit[:3]) #slice 3 awal
print(fruit[3:]) #slice 3 akhir

ban
ana

In [24]:
fruit[:] #mengambil seluruh karakter

'banana'

In [26]:
#slice dalam list
a_list = ['a', 'b', 'c', 'd', 'e', 'f']
print(a_list[1:3])
print(a_list[:4])
print(a_list[3:])
print(a_list[:])

['b', 'c']
['a', 'b', 'c', 'd']
['d', 'e', 'f']
['a', 'b', 'c', 'd', 'e', 'f']

In [27]:
#slice dalam tuple
julia = ("Julia", "Roberts", 1967, "Duplicity", 2009, "Actress", "Atlanta, Georgia")
print(julia[2])
print(julia[2:6])

print(len(julia))

julia = julia[:3] + ("Eat Pray Love", 2010) + julia[5:]
print(julia)

1967
(1967, 'Duplicity', 2009, 'Actress')
7
('Julia', 'Roberts', 1967, 'Eat Pray Love', 2010, 'Actress', 'Atlanta, Georgia')

In [28]:
s = "python rocks"
print(s[3:8])

hon r

In [29]:
alist = [3, 67, "cat", [56, 57, "dog"], [ ], 3.14, False]
print(alist[4:])

[[], 3.14, False]

In [30]:
L = [0.34, '6', 'SI106', 'Python', -2]
print(len(L[1:-1]))

3

---
Create a new list using the 9th through 12th elements (four items in all) of new_lst and assign it to the variable sub_lst.

In [31]:
new_lst = ["computer", "luxurious", "basket", "crime", 0, 2.49, "institution", "slice", "sun", ["water", "air", "fire", "earth"], "games", 2.7, "code", "java", ["birthday", "celebration", 1817, "party", "cake", 5], "rain", "thunderstorm", "top down"]

sub_lst=new_lst[8:12]
print(sub_lst)

['sun', ['water', 'air', 'fire', 'earth'], 'games', 2.7]

## 6.7. Concatenation and Repetition
---
penggabungan dan perulangan. dalam jenis data String penggabungannya dapat dilajukan dengan menggunakan operator (+). hal ini juga berlaku pada operator-operator lain seperti (*) dimana operator tersebut akan melakukan perulangan sebanyak n kali.

In [32]:
fruit = ["apple","orange","banana","cherry"]
print([1,2] + [3,4])
print(fruit+[6,7,8,9])

print([0] * 4)

[1, 2, 3, 4]
['apple', 'orange', 'banana', 'cherry', 6, 7, 8, 9]
[0, 0, 0, 0]

In [33]:
alist = [1,3,5]
blist = [2,4,6]
print(alist + blist)

[1, 3, 5, 2, 4, 6]

In [34]:
alist = [1,3,5]
print(alist * 3)

[1, 3, 5, 1, 3, 5, 1, 3, 5]